version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    networks:
      - app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    restart: always
    ports:
      - "8082:8082"
    networks:
      - app
    environment:
      JWT_SECRET: secret
      PGUSER: postgres
      PGPASSWORD: 1234
      PGDATABASE: postgres
      PGHOST: db
    depends_on:
      - db

networks:
  app:
  